name: bogoballers
description: "BogoBallers"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_native_splash: ^2.4.6
  intl_phone_number_input: ^0.7.4
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  crypto: ^3.0.6
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1
  jwt_decoder: ^2.0.1
  file_picker: ^10.1.9
  extended_image: ^10.0.1
  path: ^1.9.1
  http: ^1.4.0
  supabase_flutter: ^2.9.0
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.2.1
  shared_preferences: ^2.5.3
  flutter_tournament_bracket: ^1.0.5
  get: ^4.7.2
  iconsax_flutter: ^1.0.1
  firebase_dynamic_links: ^6.1.7
  get_it: ^8.0.3
  socket_io_client: ^3.1.2
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  multi_image_picker_view: ^3.0.0
  image_picker: ^1.1.2
  flutter_markdown: ^0.7.7+1
  flutter_riverpod: ^2.6.1
  app_links: ^6.4.0
  url_launcher: ^6.3.2
  getwidget: ^6.0.0
  flutter_secure_storage: ^9.2.4
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.3.0
  dropdown_search: ^6.0.2
  dartz: ^0.10.1
  webview_flutter: ^4.13.0
  webview_flutter_wkwebview: ^3.23.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_app_primary.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/fonts/
    - assets/images/
    - assets/json/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: TeamIcon
      fonts:
        - asset: assets/icons/team-icon.ttf
    - family: LeagueIcon
      fonts:
        - asset: assets/icons/league-icon.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter_28pt-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Inter_28pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter_28pt-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/Inter_28pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_28pt-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Inter_28pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_28pt-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_28pt-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_28pt-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Inter_28pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_28pt-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Inter_28pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter_28pt-BlackItalic.ttf
          weight: 900
          style: italic
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
